sudo: false
addons:
  firefox: "37.0.1"
before_install:
  - "export DISPLAY=:99.0"
services:
  - elasticsearch
  - redis-server
language: python
env:
  matrix:
  - TESTENV=py34
  - TESTENV=coveralls
install:
- pip install tox
- make config
script: tox -e $TESTENV
notifications:
  email:
  - opensource-tests@paylogic.com
