sudo: false
services:
  - elasticsearch
  - redis-server
language: python
env:
  matrix:
  - TESTENV=py34
  - TESTENV=coveralls
install:
- pip install tox
- make config
script: tox -e $TESTENV
notifications:
  email:
  - opensource-tests@paylogic.com
