pdt:
    django_secret_key: my-secret-key-value
    database:
        engine: django.db.backends.sqlite3
        name: db.sqlite3
        user:
        password:
        host:
        port:
    raven:
        dsn: http://some-raven-dsn
    api:
        token: some-api-token
    fogbugz:
        token: some-fogbugz-token
        url: http://fogbugz.example.com
        ci_project_field_id: cixproject
        migration_url_field_id: dbxmigration
    hostname: localhost
    debug: true
    celery:
        broker_url: redis://localhost:6379/0
        result_backend: redis://localhost:6379/0
        scheduler_url: redis://localhost:6379/1
    cache:
        redis:
            host: localhost
            port: 6379
            db: 3
