pdt:
    django_secret_key: my-secret-key-value
    database:
        engine: django.db.backends.sqlite3
        name: db.sqlite3
        user:
        password:
        host:
        port:
    raven:
        dsn: some-raven-dsn
    api:
        token: some-api-token
    fogbugz:
        token: some-fogbugz-token
        url: http://fogbugz.example.com
        ci_project_field_id: cixproject
    hostname: localhost
    debug: false
